version: '3'
services:
  redis-cache-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-cache-app
    restart: always
    environment:
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    networks:
      redisnet:
        ipv4_address: 192.169.0.2

  redis1:
    container_name: redis1
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      redisnet:
        ipv4_address: 192.169.0.3

  redis2:
    container_name: redis2
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      redisnet:
        ipv4_address: 192.169.0.4

  redis3:
    container_name: redis3
    image: redis
    ports:
      - "6381:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      redisnet:
        ipv4_address: 192.169.0.5

  redis4:
    container_name: redis4
    image: redis
    ports:
      - "6382:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      redisnet:
        ipv4_address: 192.169.0.6

  redis5:
    container_name: redis5
    image: redis
    ports:
      - "6383:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      redisnet:
        ipv4_address: 192.169.0.7

  redis6:
    container_name: redis6
    image: redis
    ports:
      - "6384:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      redisnet:
        ipv4_address: 192.169.0.8


  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis1:6379,local:redis2:6379,local:redis3:6379,local:redis4:6379,local:redis5:6379,local:redis6:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis1
      - redis2
      - redis3
      - redis4
      - redis5
      - redis-cache-app
    networks:
      redisnet:
        ipv4_address: 192.169.0.9

networks:
  redisnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.169.0.0/24
          gateway: 192.169.0.1